<?php
/**
 * @file
 * wf_user.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function wf_user_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'user-user-field_full_name'
  $field_instances['user-user-field_full_name'] = array(
    'bundle' => 'user',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Your full name.  Your name will be shown to all users.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'user',
    'field_name' => 'field_full_name',
    'label' => 'Full name',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => 1,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 0,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Full name');
  t('Your full name.  Your name will be shown to all users.');

  return $field_instances;
}
