<?php
/**
 * @file
 * Code for the wf_job_generic feature.
 */

include_once 'wf_job_generic.features.inc';

/**
 * Implements hook_menu_local_tasks_alter().
 */
function wf_job_generic_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if ($root_path == 'jobs/my' || $root_path == 'jobs/assigned') {
    $item = menu_get_item('job/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
    $tasks = array(
      'jobs/my' => t('My Jobs'),
      'jobs/assigned' => t('Assigned Jobs'),
    );
    $data['tabs'][0]['count'] = isset($data['tabs'][0]['count']) ? $data['tabs']['count'] : 0;
    foreach ($tasks as $path => $title) {
      $item = menu_get_item($path);
      if ($item['access']) {
        $data['tabs'][0]['count']++;
        $item['title'] = $title;
        $data['tabs'][0]['output'][] = array(
          '#theme' => 'menu_local_task',
          '#link' => $item,
        );
      }
    }
  }
}
