<?php

/**
 * @file
 * Workflow job module functions.
 */

/**
 * Implements hook_entity_info().
 */
function wf_job_entity_info() {
  $info = array();

  $info['wf_job'] = array(
    'label' => t('Workflow Job'),
    'entity class' => 'WfJob',
    'controller class' => 'WfJobController',
    'base table' => 'wf_job',
    'revision table' => 'wf_job_revision',
    'fieldable' => TRUE,
    'entity keys' => array(
      'bundle' => 'bundle',
      'id' => 'jid',
      'revision' => 'vid',
      'label' => 'job',
      'uuid' => 'uuid',
      'revision uuid' => 'vuuid',
    ),
    'bundle keys' => array('bundle' => 'bundle'),
    'bundles' => array(),
    'load hook' => 'wf_job_load',
    'view modes' => array(
      'full' => array(
        'label' => t('Full Job'),
        'custom settings' => FALSE,
      ),
    ),
    'label callback' => 'entity_class_label',
    'uri callback' => 'entity_class_uri',
    'module' => 'wf_job',
    'uuid' => TRUE,
    'access callback' => 'wf_job_access',
    'views controller class' => 'WfJobViewsController',
    'default_revision' => TRUE,
  );

  $info['wf_job_bundle'] = array(
    'label' => t('Job Type'),
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIControllerExportable',
    'base table' => 'wf_job_bundle',
    'fieldable' => FALSE,
    'bundle of' => 'wf_job',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'bundle',
      'name' => 'bundle',
      'label' => 'label',
      'status' => 'status',
      'module' => 'module',
    ),
    'module' => 'wf_job',
    'admin ui' => array(
      'path' => 'admin/structure/job-types',
      'file' => 'includes/wf_job.admin.inc',
    ),
    'access callback' => 'wf_job_type_access',
  );

  foreach (wf_job_load_bundles() as $name => $bundle) {
    $info['wf_job']['bundles'][$name] = array(
      'label' => $bundle->label,
      'admin' => array(
        'path' => 'admin/structure/job-types/manage/%',
        'real path' => 'admin/structure/job-types/manage/' . $name,
        'bundle argument' => 4,
        'access arguments' => array('administer jobs'),
      ),
    );
  }

  return $info;
}

/**
 * Implements hook_menu().
 */
function wf_job_menu() {
  $items = array();
  $items['job/add'] = array(
    'title' => 'New job',
    // Grant the user access to this page regardless of other permissions.
    'access callback' => TRUE,
    'page callback' => 'wf_job_page_add',
    'file' => 'includes/wf_job.pages.inc',
  );

  foreach (array_keys(wf_job_load_bundles()) as $bundle) {
    $items['job/add/' . $bundle] = array(
      'title' => 'New job',
      'page callback' => 'wf_job_add',
      'page arguments' => array(2),
      'access callback' => 'entity_access',
      'access arguments' => array('create', 'wf_job', $bundle),
      'file' => 'includes/wf_job.pages.inc',
    );
  }

  $items['job/%wf_job'] = array(
    'title callback' => 'wf_job_page_title',
    'title arguments' => array(1),
    'access callback' => 'entity_access',
    'access arguments' => array('view', 'wf_job', 1),
    'page callback' => 'wf_job_view',
    'page arguments' => array(1),
    'file' => 'includes/wf_job.pages.inc',
  );
  $items['job/%wf_job/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['job/%wf_job/edit'] = array(
    'title' => 'Edit',
    'access callback' => 'entity_access',
    'access arguments' => array('edit', 'wf_job', 1),
    'page callback' => 'wf_job_edit',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/wf_job.pages.inc',
  );
  $items['job/%wf_job/delete'] = array(
    'title' => 'Delete',
    'access callback' => 'entity_access',
    'access arguments' => array('delete', 'wf_job', 1),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wf_job_delete_form', 1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/wf_job.pages.inc',
    'weight' => 10,
  );
  $items['job/%wf_job/start'] = array(
    'title callback' => 'wf_job_action_title',
    'title arguments' => array(1, 'start'),
    'access callback' => 'wf_job_action_allowed',
    'access arguments' => array(1, 'start'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wf_job_action_start_form', 1),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'includes/wf_job.admin.inc',
    'weight' => -10,
  );
  $items['job/%wf_job/propose'] = array(
    'title callback' => 'wf_job_action_title',
    'title arguments' => array(1, 'propose'),
    'access callback' => 'wf_job_action_allowed',
    'access arguments' => array(1, 'propose'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wf_job_action_propose_form', 1),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'includes/wf_job.admin.inc',
    'weight' => -10,
  );
  $items['job/%wf_job/review'] = array(
    'title callback' => 'wf_job_action_title',
    'title arguments' => array(1, 'review'),
    'access callback' => 'wf_job_action_allowed',
    'access arguments' => array(1, 'review'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wf_job_action_review_form', 1),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'includes/wf_job.admin.inc',
    'weight' => -10,
  );
 $items['job/%wf_job/visit'] = array(
    'title' => 'Visit Sandbox',
    'access callback' => 'wf_job_action_allowed',
    'access arguments' => array(1, 'visit'),
    'page callback' => 'wf_job_visit',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_ACTION,
    'weight' => 10,
  );
  $items['job/%wf_job/login'] = array(
    'title' => 'Login to dev sandbox',
    'access callback' => 'wf_job_action_allowed',
    'access arguments' => array(1, 'login'),
    'page callback' => 'wf_job_job_sandbox_login_page',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_ACTION,
    'weight' => 20,
  );
  $items['job/%wf_job/update-code'] = array(
    'title' => 'Update code',
    'access callback' => 'wf_job_action_allowed',
    'access arguments' => array(1, 'update_code'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wf_job_update_job_code_form', 1),
    'type' => MENU_LOCAL_ACTION,
    'weight' => 50,
  );
   $items['admin/content/jobs/drush-aliases'] = array(
    'title' => 'Download drush aliases',
    'description' => 'Admin page for exporting drush wf.aliases.drushrc.php file',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wf_job_export_drush_aliases_form'),
    'access arguments' => array('export job aliases'),
    'type' => MENU_LOCAL_TASK | MENU_NORMAL_ITEM,
    'file' => 'includes/wf_job.pages.inc',
  );
  $items['admin/structure/job-types/manage/%wf_job_type'] = array(
    'title' => 'Config job type',
    'access arguments' => array('administer jobs'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bundle_key_form', 4),
    'type' => MENU_CALLBACK,
    'file' => 'example.admin.inc',
  );
  $items['admin/structure/job-types/manage/%wf_job_type/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/config/development/wf_job'] = array(
    'title' => 'WF Job',
    'description' => 'Configure job settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wf_job_admin_settings'),
    'access arguments' => array('administer jobs'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/wf_job.admin.inc',
  );
  return $items;
}


/**
 * Implements hook_permission().
 */
function wf_job_permission() {
  $perms = array();

  $perms['administer job types'] = array(
    'title' => t('Administer jobs'),
    'description' => t('Administer job types and configuration'),
  );

  $perms['manage jobs'] = array(
    'title' => t('Manage jobs'),
    'description' => ('Create, edit or delete any job'),
  );

  foreach (array_keys(wf_job_load_bundles()) as $bundle) {
    $perms += wf_job_list_permissions($bundle);
  }

  $envs = wf_environment_list_names(TRUE, variable_get('wf_environment_default'));
  $actions = array('propose job for', 'rewiew job before');
  foreach ($envs as $env) {
    foreach ($actions as $action) {
      $key = filter_xss("{$action} {$env}");
      $perms[$key] = array(
        'title' => filter_xss(ucfirst($key)),
      );
    }
  }

  $perms['review own jobs'] = array(
    'title' => t('Review own jobs'),
  );


  return $perms;
}

/**
 * Helper function to create wf_job permission list for a given wf_job type.
 *
 * @param string $type
 *   The machine-readable name of the wf_job type.
 *
 * @return array
 *   An array of permission names and descriptions.
 */
function wf_job_list_permissions($type) {
  // Build standard list of wf_job permissions for this wf_job type.
  $actions = array('view', 'edit', 'delete', 'login', 'visit', 'update code');

  $perms = array();
  $perms["create $type job"] = array(
    'title' => t(
      '%type_name: Create new job',
      array('%type_name' => $type)
    ),
  );
  foreach ($actions as $action) {
    $perms["$action own $type job"] = array(
      'title' => t(
        '%type_name: %action own job', array(
          '%action' => ucfirst($action),
          '%type_name' => $type,
        )
      ),
    );
    $perms["$action any $type job"] = array(
      'title' => t(
        '%type_name: %action any job', array(
          '%action' => ucfirst($action),
          '%type_name' => $type,
        )
      ),
    );
  }
  return $perms;
}

/**
 * Returns whether the current user is allowed to perform the $action on the given $job at this time.
 *
 * @param WfJob $job
 * @param string $action
 *
 * @return bool
 */
function wf_job_action_allowed($job, $action) {
  return wf_job_action_allowed_by_user($job, $action) && wf_job_action_allowed_in_current_state($job, $action);
}

/**
 * Returns whether the current user is allowed to perform the $action on the given $job.
 *
 * @param WfJob $job
 * @param string $action
 *
 * @return bool
 */
function wf_job_action_allowed_by_user($job, $action) {
  global $user;

  $is_admin = user_access('administer jobs');
  if ($is_admin) {
    return TRUE;
  }

  $type = $job->bundle;

  switch ($action) {
    /*
    case 'change_environment':
    case 'change_status':
      return $is_admin;
    */

    case 'change_owner':
    case 'assign':
      return TRUE;

    case 'start':
    case 'propose':
    case 'edit':
      return wf_job_access('edit', $job, $user, $type);

    case 'update_code':
      return user_access("update code job any {$type}") || (user_access("update code job own {$type}") && $job->owner == $user->uid);

    // FIXME: Implement proper permission checks for propose/review
    case 'propose':
    case 'review':
    case 'approve':
    case 'reject':
      return wf_job_access('review', $job, $user, $type) && $job->assigned == $user->uid;

    case 'login':
    case 'visit':
      return wf_job_access($action, $job, $user, $type);
  }

  return FALSE;
}

/**
 * Returns whether the $action is allowed for the $job in its current state.
 *
 * @param WfJob $job
 * @param string $action
 *
 * @return boolean
 */
function wf_job_action_allowed_in_current_state($job, $action) {
  $statuses = wf_job_status_list();
  $jsid = empty($job->jsid) ? 1 : $job->jsid;
  $status = $statuses[$jsid];
  $env = wf_environment_load($job->eid);
  $has_next_env = !empty($env->next_env_id);
  $is_default_env = ($job->eid == wf_environment_get_default());

  switch ($action) {
    case 'change_environment':
    case 'change_status':
    case 'change_owner':
    case 'assign':
      return TRUE;

    case 'start':
      return $is_default_env && $status == 'New';

    case 'login':
    case 'update_code':
      return $is_default_env && $status == 'Started';

    case 'propose':
      return $has_next_env && $status == 'Started';

    case 'review':
    case 'approve':
    case 'reject':
      return $has_next_env && $status == 'In Review';

    case 'visit':
       return !in_array($status, array('New', 'Completed')) && $has_next_env;
  }
  return FALSE;
}


/**
 * Access callback for the entity API.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $entity
 *   (optional) A profile to check access for. If nothing is given, access for
 *   all profiles is determined.
 * @param $account
 *   (optional) The user to check for. Leave it to NULL to check for the global user.
 * @param $entity_type
 *   (optional) Leave it to NULL to get the property from $entity.
 *
 * @return boolean
 *   Whether access is allowed or not.
 */
function wf_job_access($op, $entity, $account = NULL, $entity_type = NULL) {
  $has_access = FALSE;

  if (!isset($account)) {
    global $user;
    $account = $user;
  }

  // Access for admin user.
  if (1 === $account->uid) {
    return TRUE;
  }

  if (!isset($entity_type)) {
    $entity_type = $entity->type;
  }

  if (user_access('manage jobs', $account)) {
    return TRUE;
  }

  switch ($op) {
    case 'create':
      $perm = 'create ' . $entity_type . ' job';
      return  user_access($perm, $account);

    case 'view':
    case 'edit':
    case 'delete':
      return wf_job_granular_access($op, $entity_type, $entity, $account);
  }

  return FALSE;
}

/**
 * Helper function to check for granular permissions for the job type.
 *
 * @param string $action
 *   Action being executed.
 * @param string $type
 *   Current job type.
 * @param object $job
 *   Current job.
 * @param object $user
 *   User account to check the permission.
 *
 * @return boolean
 *   $user can perform this $action on this job $type.
 */
function wf_job_granular_access($action, $type, $job, $user) {
  $perm = "{$action} any {$type} job";

  if (user_access($perm, $user)) {
    return TRUE;
  }

  $perm = "{$action} own {$type} job";
  return $user->uid == $job->owner && user_access($perm, $user);
}

/**
 * Access callback for the entity API.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $profile
 *   (optional) A profile to check access for. If nothing is given, access for
 *   all profiles is determined.
 * @param $account
 *   (optional) The user to check for. Leave it to NULL to check for the global user.
 *
 * @return boolean
 *   Whether access is allowed or not.
 */
function wf_job_type_access($op, $type = NULL, $account = NULL) {
  return user_access('administer jobs', $account);
}

/**
 * Implements hook_views_api().
 */
function wf_job_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Page callback for job/%wf_job/update-code.
 */
function wf_job_update_job_code_form($form, $form_state, $job) {
  $job_uri = entity_uri('wf_job', $job);

  return confirm_form(
    $form,
    t('Are you sure you want to update the code for job <strong>@job</strong>', array('@job' => entity_label('wf_job', $job))),
    $job_uri['path'],
    t('This action takes at least a few minutes to complete.'),
    t('Update code'),
    t('Cancel')
  );
}

/**
 * Submit handler for wf_job_update_job_code_form.
 */
function wf_job_update_job_code_form_submit($form, &$form_state) {
  // Gets the current job and fires wf_job_update_code_submit rules event.
  // Then redirects to the view of the job.
  $job = reset($form_state['build_info']['args']);

  rules_invoke_event('wf_job_update_code_submit', $job);

  $uri = entity_uri('wf_job', $job);
  $form_state['redirect'] = url($uri['path'], $uri['options']);

  drupal_set_message(t('A code update for this job will commence shortly.'));
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function wf_job_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link to 'job/add' on 'admin/content/jobs' page.
  if ($root_path == 'admin/content/jobs') {
    $item = menu_get_item('job/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Implements hook_admin_paths().
 */
function wf_job_admin_paths() {
  $paths = array(
    'job/*/edit' => TRUE,
    'job/*/delete' => TRUE,
    'job/*/revisions' => TRUE,
    'job/add' => TRUE,
    'job/add/*' => TRUE,
  );
  return $paths;
}

/**
 * Implements hook_entity_property_info().
 */
function wf_job_entity_property_info() {

  $info = array();
  $properties = array();

  $properties['jid'] = array(
    'label' => t('ID'),
    'type' => 'integer',
    'description' => t('The unique job identifier.'),
    'schema field' => 'jid',
    'wf_extra_fields' => array('display'),
  );

  $properties['vid'] = array(
    'label' => t('Revision ID'),
    'type' => 'integer',
    'description' => t('The unique job revision identifier.'),
    'schema field' => 'vid',
    'wf_extra_fields' => array('form'),
  );

  $properties['uuid'] = array(
    'label' => t('UUID'),
    'type' => 'integer',
    'description' => t('The universally unique job identifier.'),
    'schema field' => 'uuid',
    'wf_extra_fields' => array('form'),
  );

  $properties['vuuid'] = array(
    'label' => t('Revision UUID'),
    'type' => 'integer',
    'description' => t('The universally unique job revision identifier.'),
    'schema field' => 'vuuid',
    'wf_extra_fields' => array(),
  );

  $properties['bundle'] = array(
    'label' => t('Bundle'),
    'type' => 'text',
    'description' => t('The job bundle.  This value is always job.'),
    'schema field' => 'bundle',
    'wf_extra_fields' => array('display'),
  );

  $properties['title'] = array(
    'label' => t('Title'),
    'type' => 'text',
    'description' => t('The name of the job.'),
    'schema field' => 'title',
    'wf_extra_fields' => array('form', 'display'),
  );

  $properties['reference'] = array(
    'label' => t('External Reference'),
    'type' => 'text',
    'description' => t('A reference identifier for the job in another system.'),
    'schema field' => 'reference',
    'wf_extra_fields' => array('form', 'display'),
  );

  $properties['details'] = array(
    'label' => t('Details'),
    'type' => 'text',
    'description' => t('Detailed notes about the job.'),
    'schema field' => 'reference',
    'wf_extra_fields' => array('form', 'display'),
  );

  $properties['jsid'] = array(
    'label' => t('Status'),
    'type' => 'integer',
    'description' => t('The current status of the job.'),
    'options list' => 'wf_job_status_list',
    'schema field' => 'jsid',
    'wf_extra_fields' => array('form', 'display'),
  );

  $properties['owner'] = array(
    'label' => t('Owner'),
    'type' => 'user',
    'description' => t('The user who owns the job.'),
    'schema field' => 'owner',
    'wf_extra_fields' => array('form', 'display'),
  );

  $properties['assigned'] = array(
    'label' => t('Assignee'),
    'type' => 'user',
    'description' => t('The user who the job is currently assigned to.'),
    'schema field' => 'assigned',
    'wf_extra_fields' => array('form', 'display'),
  );

  $properties['eid'] = array(
    'label' => t('Environment'),
    'type' => 'wf_environment',
    'description' => t('The current environment for the job.'),
    'schema field' => 'eid',
    'wf_extra_fields' => array('form', 'display'),
  );

  $properties['created'] = array(
    'label' => t('Created'),
    'type' => 'date',
    'description' => 'Date when the job was created',
    'schema field' => 'created',
    'wf_extra_fields' => array('form', 'display'),
  );

  $properties['modified'] = array(
    'label' => t('Modified'),
    'type' => 'date',
    'description' => 'Date when the job was last modified',
    'schema field' => 'created',
    'wf_extra_fields' => array('form', 'display'),
  );

  $properties['url'] = array(
    'label' => t('URL'),
    'description' => t("The URL of the job's view page."),
    'getter callback' => 'wf_job_entity_metadata_get_properties',
    'type' => 'uri',
    'computed' => TRUE,
    'wf_extra_fields' => array('form', 'display'),
  );

  $properties['edit_url'] = array(
    'label' => t('Edit URL'),
    'description' => t("The URL of the job's edit page."),
    'getter permission' => 'manage jobs',
    'getter callback' => 'wf_job_entity_metadata_get_properties',
    'type' => 'uri',
    'computed' => TRUE,
    'wf_extra_fields' => array('form', 'display'),
  );

  $info['wf_job'] = array('properties' => $properties);
  $info['wf_job_bundle'] = array('properties' => array());

  return $info;
}

/**
 * Implements hook_field_extra_fields().
 */
function wf_job_field_extra_fields() {
  return wf_generate_extra_fields('wf_job');
}

/**
 * Checks if a bundle exists.
 *
 * @param $name
 *   The bundle to look up.
 *
 * @return bool
 *   Does the bundle exist?
 */
function wf_job_bundle_exists($name) {
  $bundles = wf_job_load_bundles();
  return isset($bundles[$name]);
}

/**
 * Returns all defined job bundles.
 *
 * @return array
 */
function wf_job_load_bundles() {
  $cache = &drupal_static(__FUNCTION__);

  if (!isset($cache)) {
    $cache = db_select('wf_job_bundle', 'wjb')
      ->fields('wjb')
      ->orderBy('bundle')
      ->execute()
      ->fetchAllAssoc('bundle');
  }

  return $cache;
}

// Entity CRUD

/**
 * Creates a new job object.
 */
function wf_job_create($values = array()) {
  return entity_create('wf_job', $values);
}

/**
 * Deletes a job object.
 */
function wf_job_delete(WfJob $job) {
  $job->delete();
}

/**
 * Deletes multiple jobs.
 *
 * @param $ids array
 *   A list of job ids to delete.
 */
function wf_job_delete_multiple(array $ids) {
  entity_delete('wf_job', $ids);
}

/**
 * Loads a job object.
 */
function wf_job_load($id = NULL, $reset = FALSE) {
  $ids = (isset($id) ? array($id) : array());
  $job = wf_job_load_multiple($ids, $reset);
  return $job ? reset($job) : FALSE;
}

/**
 * Loads one or more job objects.
 */
function wf_job_load_multiple($ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('wf_job', $ids, $conditions, $reset);
}


/**
 * Saves a job.
 *
 * @param $job WfJob
 * The job to save.
 */
function wf_job_save($job) {
  $job->modified = REQUEST_TIME;
  if (empty($job->jid) || !empty($job->is_new)) {
    $job->created = REQUEST_TIME;
    $job->uid = $GLOBALS['user']->uid;
  }
  entity_save('wf_job', $job);
}

// /Entity CRUD

/**
 * Look up a job id using the reference value.
 *
 * @param $ref string
 *  The reference to look up.
 *
 * @return array
 *   List of ids found.
 */
function wf_job_id_by_reference($ref) {
  $query = new EntityFieldQuery();
  $jobs = $query->entityCondition('entity_type', 'wf_job')
    ->propertyCondition('reference', $ref)
    ->execute();

  return $jobs;
}

/**
 * Fetches a list of job status values.
 *
 * @return array
 *   List of job statuses.
 */
function wf_job_status_list() {
  $statuses = &drupal_static(__FUNCTION__);
  if (empty($statuses)) {
    $cached = cache_get('wf_job_status_list');
    if ($cached) {
      $statuses = $cached->data;
    }
    else {
      $statuses = db_select('wf_job_status', 'wfs')
        ->fields('wfs')
        ->orderBy('jsid')
        ->execute()
        ->fetchAllKeyed();
      cache_set('wf_job_status_list', $statuses, 'cache');
    }
  }
  return $statuses;
}

function wf_job_preprocess_wf_job(&$variables) {
  $sanitize = array(
    'jid',
    'title',
    'details',
  );

  $external_reference = $variables['elements']['#job']->reference;
  $reference = '';
  $plugin = variable_get('wf_job_ext_ref_plugin');
  if (!$plugin && $external_reference) {
    $sanitize[] = 'reference';
    $reference = $external_reference;
  }
  elseif ($plugin && $external_reference) {
    $class = ctools_plugin_load_class('wf_job', 'external_reference', $plugin, 'handler');
    $hander = new $class();
    $render = $hander->generateExternalRef($variables['elements']['#job']);
    if (!empty($render)) {
      $reference = drupal_render($render);
    }
  }
  $variables['elements']['#job']->reference = $reference;

  foreach ($sanitize as $var) {
    $variables['elements']['#job']->{$var} = check_plain($variables['elements']['#job']->{$var});
  }

  $variables['elements']['owner_name'] = theme('username', array('account' => user_load($variables['elements']['#job']->owner)));
  $variables['elements']['assigned_name'] = theme('username', array('account' => user_load($variables['elements']['#job']->assigned)));
  $variables['elements']['created_date'] = format_date($variables['elements']['#job']->created);
}

/**
 * Provides a job sandbox uri.
 *
 * @param $job WfJob
 * The job for which a sandbox URI is sought
 */
function wf_job_sandbox_uri($job, $path = '') {
  // TODO make this pluggable.
  $slug = wf_job_slug($job->jid);
  $dev_env = wf_environment_dev();
  return wf_environment_app_uri($dev_env, $job);
}

/**
 * Provides the drush aliases for all current jobs.
 *
 * @return array
 * An array of aliases
 */
function wf_job_drush_aliases() {
  $new_id = variable_get('wf_job_jsid_new');
  $completed_id = variable_get('wf_job_jsid_completed');

  $query = new EntityFieldQuery();
  // Implement hook_entity_query_alter() if you need to change this.
  $jids = $query->entityCondition('entity_type', 'wf_job')
        ->propertyCondition('jsid', array($new_id, $completed_id), 'NOT IN')
        ->propertyOrderBy('jid')
        ->execute();

  $jobs = array();
  if (!empty($jids['wf_job'])) {
    $jobs = entity_load('wf_job', array_keys($jids['wf_job']));
  }

  $aliases = array(
    'job' => array(
      'remote-host' => variable_get('wf_sandbox_remote_host', 'localhost'),
    ),
  );

  foreach ($jobs as $job) {
    $job_uri = wf_job_sandbox_uri($job);
    $slug = wf_job_slug($job->jid);
    $aliases[$slug] = array(
      'parent' => '@job',
      'uri' => preg_replace('#^https?://#', '', $job_uri['path']),
      'root' => variable_get('wf_sandbox_basepath', '/srv/www') . "/$slug/",
    );
    $aliases[$job->reference] = array(
      'parent' => "@$slug",
    );
  }

  drupal_alter('wf_job_drush_aliases', $aliases);
  return $aliases;
}

/**
 * Implements hook_theme().
 */
function wf_job_theme() {
  $themes = array();
  $templates = drupal_get_path('module', 'wf_job') . '/includes';

  $themes['wf_job_add_list'] = array(
    'file' => 'wf_job.theme.inc',
    'variables' => array('content' => NULL),
    'path' => $templates,
  );

  $themes['wf_job_drush_aliases'] = array(
    'file' => 'wf_job.theme.inc',
    'variables' => array(
      'aliases' => array(),
    ),
    'path' => $templates,
  );

  $themes['wf_job'] = array(
    'file' => 'wf_job.theme.inc',
    'render element' => 'elements',
    'template' => 'wf_job',
    'path' => $templates,
  );

  return $themes;
}

/**
 * Provides the names of all users.
 *
 * @param string key
 *   A key into the 'job_users' view to select different lists of users. If
 *   omitted the default list is for all active users. Supported values include:
 *   - review_others
 *
 * @return array
 */
function wf_job_users($permission = 'manage jobs') {

  // Load the view and apply the filter.
  $view = views_get_view('job_users');
  $view->set_display('block');
  $view->exposed_input['permission'] = $permission;

  // Run the view
  $view->pre_execute();
  $view->execute();

  $users = array();
  foreach ($view->result as $result) {
    $users[$result->uid] = $result->realname_realname;
  }
  return $users;
}


/**
 * Provides the title of a menu callback.
 */
function wf_job_action_title($job, $action) {
  switch ($action) {
    case 'propose':
    case 'approve':
      $env = wf_environment_load($job->eid);
      if (empty($env->next_env_id)) {
        drupal_set_message(t("There is no next environment after @env", array('@env' => $env->env)), 'error');
      }
      else {
        $next_env = wf_environment_load($env->next_env_id);
        return t('@action for @environment', array('@action' => ucfirst($action), '@environment' => $next_env->env));
      }
    default:
      return t(ucfirst($action));
  }
}

/**
 * Trigger event notifications for job actions.
 */
function wf_job_action_event_invoke($event, $job) {
  $owner = user_load($job->owner);
  $assigned = user_load($job->assigned);
  $env = wf_environment_load($job->eid);
  $next_env = FALSE;

  if (!empty($env->next_env_id)) {
    $next_env = wf_environment_load($env->next_env_id);
  }

  if (empty($next_env)) {
    $next_env = entity_create('wf_environment', array('env' => 'None'));
  }

  rules_invoke_event_by_args("wf_job_$event", array(
    'job' => $job,
    'environment' => $env,
    'next_environment' => $next_env,
    'owner' => $owner,
    'assigned' => $assigned,
  ));
}

/**
 * Records the outcome of a deployment.
 *
 * @param object $job
 *   The WfJob
 * @param bool $succeeded
 *   Whether the deployment succeeded
 * @param string $message
 *   A comment about the deployment outcome.
 * @return
 *   TRUE
 */
function wf_job_deployment($job, $succeeded, $message) {
  $env = wf_environment_load($job->eid);
  $next_env = wf_environment_load($env->next_env_id);

  if ($succeeded) {
    $job->eid = $env->next_env_id;
    if ($next_env->next_env_id) {
      $job->setStatusName('Started');
      $rules_event = 'deployed';
    }
    else {
      $job->setStatusName('Completed');
      $rules_event = 'completed';
    }
  }
  else {
    $job->setStatusName('Needs Attention');
    $rules_event = 'deployment_failed';
  }

  $job->rules_event = $rules_event;
  $job->log = filter_xss_admin($message);

  wf_job_save($job);

  return TRUE;
}

/**
 * Implements hook_block_info().
 */
function wf_job_block_info() {
  $blocks = array();

  $blocks['wf_job_env_status'] = array(
    'info' => t('Job environment status'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function wf_job_block_view($delta) {
  switch ($delta) {
    case 'wf_job_env_status':
      return wf_job_env_status_block();
  }
}

/**
 * Returns a the wf_job_env_status block.
 */
function wf_job_env_status_block() {
  $items = array();

  $job = menu_get_object('wf_job');
  if (empty($job)) {
    return array();
  }

  $statuses = wf_job_status_list();
  $status = $statuses[$job->jsid];
  $class = array('passed');

  foreach(wf_environment_list() as $id => $env) {
    if ($job->eid == $id) {
      $class = array('current', preg_replace('/[^a-z0-1]+/', '-', strtolower($status)));
      $items[] = array('data' => t('@env: @status', array('@env' => $env->env, '@status' => $status)), 'class' => $class);
      $class = array('future');
      continue;
    }
    $items[] = array('data' => $env->env, 'class' => $class);
  }

  return array(
    'subject' => t('Job progress'),
    'content' => array(
      '#theme' => 'item_list',
      '#items' => $items,
      '#attributes' => array('class' => array('job-env-status')),
    ),
  );
}

/**
 * Implements hook_entity_insert().
 */
function wf_job_entity_insert($entity, $entity_type) {
  wf_job_entity_update($entity, $entity_type);
}

/**
 * Implements hook_entity_update().
 */
function wf_job_entity_update($entity, $entity_type) {
  if ('wf_job' == $entity_type) {
    if (!empty($entity->rules_event)) {
      wf_job_action_event_invoke($entity->rules_event, $entity);
    }
  }
}

/**
 * Returns a slug for the given job id.
 *
 * @param int $job_id
 */
function wf_job_slug($jid) {
  return format_string(variable_get('wf_job_slug_pattern', 'job@jid'), array('@jid' => $jid));
}

/**
 * Callback for getting properties of an entity.
 */
function wf_job_entity_metadata_get_properties($entity, array $options, $name, $entity_type) {
  switch ($name){
    case 'url':
      $return = entity_uri($entity_type, $entity);
      return url($return['path'], $return['options'] + $options);

    case 'edit_url':
      $return = entity_uri($entity_type, $entity);
      return url($return['path'] . '/edit', $return['options'] + $options);

  }
}

/**
 * Redirects the user to view the sandbox site.
 */
function wf_job_visit(WfJob $job) {
  ctools_include('plugins');

  $plugin = variable_get('wf_job_visit_plugin');
  if (!$plugin) {
    drupal_set_message(t('View sandbox plugin undefined.'), 'error');
    $uri = entity_uri('wf_job', $job);
    return drupal_goto($uri['path'], $uri['options']);
  }

  $class_name = ctools_plugin_load_class('wf_job', 'url_visit', $plugin, 'handler');
  $handler = new $class_name();

  $url = $handler->generateVisitLink($job);
  drupal_goto($url);
}

/**
 * Implements hook_ctools_plugin_api().
 */
function wf_job_ctools_plugin_api($module, $api) {
  $apis = array(
    'sandbox_domain',
    'url_login',
    'url_visit',
    'url_ssh',
    'external_reference',
  );

  if ('wf_job' == $module && in_array($api, $apis)) {
    return array('version' => 1);
  }
}

/**
 * Implements hook_ctools_plugin_type().
 */
function wf_job_ctools_plugin_type() {
  $apis = array(
    'sandbox_domain',
    'url_login',
    'url_visit',
    'url_ssh',
    'external_reference',
  );

  $plugins = array();
  foreach ($apis as $api) {
    $plugins[$api] = array(
      'classes' => array('handler'),
    );
  }

  return $plugins;
}

/**
 * Default implementation for accessing a job sandbox.
 *
 * @param object $job
 *   The object of the related Job entity.
 */
function wf_job_job_sandbox_login_page($job) {
  // TODO implement redirect here using drupal_goto.
  return t('You should be redirected to your job.');
}

/**
 * Fetches a list of plugins.
 *
 * @param  string $type
 *   The plugin type.
 * @return array
 *   An associative array of plugins keyed by name.
 */
function wf_job_get_plugins_list($type) {
  $plugins = array();
  foreach (ctools_get_plugins('wf_job', $type) as $name => $info) {
    $plugins[$name] = $info['title'];
  }
  return $plugins;
}

/**
 * Implements hook_wf_log_info().
 */
function wf_job_wf_log_info() {
  $logs = array();

  $logs['wf_job_started'] = array(
    'title' => t('Job started'),
    'description' => t('A new Job was started.'),
  );

  $logs['wf_job_proposed'] = array(
    'title' => t('Job proposed'),
    'description' => t('Job was proposed for review.'),
  );

  $logs['wf_job_saved'] = array(
    'title' => t('Job saved'),
    'description' => t('Job was saved.'),
  );

  $logs['wf_job_approved'] = array(
    'title' => t('Job approved'),
    'description' => t('Job was approved.'),
  );

  $logs['wf_job_rejected'] = array(
    'title' => t('Job rejected'),
    'description' => t('Job was rejected.'),
  );

  $logs['wf_job_deployed'] = array(
    'title' => t('Job deployed'),
    'description' => t('Job was deployed to a new environment.'),
  );

  $logs['wf_job_deployment_failed'] = array(
    'title' => t('Job deployment failed'),
    'description' => t('Job\'s deployment to a new environment fails.'),
  );

  $logs['wf_job_completed'] = array(
    'title' => t('Job completed'),
    'description' => t('Job was deployed to the final environment.'),
  );

  $logs['wf_job_update_code_submit'] = array(
    'title' => t('"Update code" button clicked'),
    'description' => t('User clicked on the Update code button.'),
  );

  $logs['wf_job_start_update_code'] = array(
    'title' => t('Code update started'),
    'description' => t('Code update was started for a job.'),
  );

  $logs['wf_job_updated_code'] = array(
    'title' => t('Job code updated'),
    'description' => t('Job code has been updated.'),
  );

  return $logs;
}

/**
 * Update the status of a job.
 */
function wf_job_update_status(WfJob $job, $status_id) {
  $job->jsid = $status_id;
  wf_job_save($job);
}

/**
 * Update the environment for a job.
 */
function wf_job_update_environment(WfJob $job, $env_id) {
  $job->eid = $env_id;
  wf_job_save($job);
}
