<?php
/**
 * @file
 * Code for the wf_jenkins feature. Drupal requires this blank file.
 */

/**
 * The Action function for 'wf_jenkins_update_code_submit'.
 */
function wf_jenkins_update_code_submit($job) {
  wf_jenkins_start_update_code($job);
}

/**
 * Inform Drupal that a job's code has been updated.
 */
function wf_jenkins_updated_code($job, $succeeded) {
  $outcome = ($succeeded ? 'completed' : 'failed');
  $reply = wf_job_reply_save(
    $job,
    t('Job code update @outcome', array('@outcome' => $outcome)),
    t('A code update has @outcome.', array('@outcome' => $outcome))
  );

  wf_jenkins_action_event_invoke('updated_code', $job);
}

/**
 * Inform Drupal that a job's code has been updated.
 */
function wf_jenkins_start_update_code($job) {
  $path = 'job/update-code/buildWithParameters';
  $query = array(
    'GIT_BRANCH' => wf_job_slug($job->jid),
  );
  // Schedule the code update in Jenkins.
  jenkins_request($path, $query);

  drupal_set_message(t('A code update for this job has commenced'));
  $reply = wf_job_reply_save($job, t('Starting code update'), t('A code update has commenced.'));

  wf_jenkins_action_event_invoke('start_update_code', $job);
}

/**
 * Trigger a rules event for the given job.
 */
function wf_jenkins_action_event_invoke($event, $job) {
  $owner = user_load($job->owner);
  $assigned = user_load($job->assigned);
  $env = wf_environment_load($job->eid);

  rules_invoke_event_by_args("wf_job_$event", array(
    'job' => $job,
    'environment' => $env,
    'owner' => $owner,
    'assigned' => $assigned,
  ));
}
