<?php
/**
 * @file
 * Code for the wf_jenkins feature. Drupal requires this blank file.
 */

/**
 * Implements hook_menu().
 */
function wf_jenkins_menu() {
  $items = array();

  $items['job/%wf_job/update-code'] = array(
    'title' => t('Update code'),
    'access arguments' => array('update job sandbox code'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wf_jenkins_update_job_code_form', 1),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function wf_jenkins_permission() {
  $perms = array();

  $perms['update job sandbox code'] = array(
    'title' => t('Update job sandbox code'),
  );

  return $perms;
}

/**
 * Page callback for job/%wf_job/update-code
 */
function wf_jenkins_update_job_code_form($form, $form_state, $job) {
  $job_uri = entity_uri('wf_job', $job);
  return confirm_form(
    $form,
    t('Are you sure you want to update the code for job <strong>@job</strong>', array('@job' => entity_label('wf_job', $job))),
    $job_uri['path'],
    t('This action takes at least a few minutes to complete.'),
    t('Update code'),
    t('Cancel')
  );
}

/**
 * Submit handler for wf_jenkins_update_job_code_form.
 */
function wf_jenkins_update_job_code_form_submit($form, &$form_state) {
  $job = reset($form_state['build_info']['args']);
  wf_jenkins_start_update_code($job);
}

/**
 * Inform Drupal that a job's code has been updated.
 */
function wf_jenkins_updated_code($job, $succeeded) {
  $outcome = ($succeeded ? 'completed' : 'failed');
  $reply = wf_job_reply_save(
    $job,
    t('Job code update @outcome', array('@outcome' => $outcome)),
    t('A code update has @outcome.', array('@outcome' => $outcome))
  );

  wf_jenkins_action_event_invoke('updated_code', $job);
}

/**
 * Inform Drupal that a job's code has been updated.
 */
function wf_jenkins_start_update_code($job) {
  $path = 'job/update-code/buildWithParameters';
  $query = array(
    'GIT_BRANCH' => wf_job_slug($job->jid),
  );
  // Schedule the code update in Jenkins
  jenkins_request($path, $query);

  drupal_set_message(t('A code update for this job has commenced'));
  $reply = wf_job_reply_save($job, t('Starting code update'), t('A code update has commenced.'));

  wf_jenkins_action_event_invoke('start_update_code', $job);
}

/**
 * Trigger a rules event for the given job.
 */
function wf_jenkins_action_event_invoke($event, $job) {
  $owner = user_load($job->owner);
  $assigned = user_load($job->assigned);
  $env = wf_environment_load($job->eid);

  rules_invoke_event_by_args("wf_jenkins_$event", array(
    'job' => $job,
    'environment' => $env,
    'owner' => $owner,
    'assigned' => $assigned,
  ));
}
